# BIOMATH 208 PSEt 4

Simon Lee (simonlee711@g.ucla.edu)

# 1 Geodesics

## 1.1 The length of a curve is parameterization invariant

Let $ M $ be a Riemannian manifold, and let $ \gamma : [0,1] \to M $ be a curve. The length of the curve is given by

$$
L[\gamma] = \int_0^1 \sqrt{g_{\gamma(t)}(\dot{\gamma}(t), \dot{\gamma}(t))} \, dt
$$

for a Riemannian metric (0,2) tensor field $ g $. In a coordinate chart $ x $ we write $ q(t) = \gamma(x(t)) $ and components $ g_{ij}(q(t)) = g_{x^{-1}(q(t))} \left( \frac{\partial}{\partial x_i}, \frac{\partial}{\partial x_j} \right) $. In coordinates we can write the length functional as

$$
L[\gamma] = \int_0^1 \sqrt{g_{ij}(q(t))\dot{q}^i(t)\dot{q}^j(t)} \, dt
$$

Show that the length is reparameterization invariant. That is, show that for a smooth monotonically increasing invertible transformation $ \phi : [0,1] \to [0,1] $, with inverse $ \phi^{-1} $, we have $ L[\gamma] = L[\gamma \circ \phi] $.


## <span style="color:green">Answer

To demonstrate that the length of a curve $\gamma$ on a Riemannian manifold $M$ is invariant under reparameterization, we start by considering a new parameterization of the curve $\gamma$ via a smooth, monotonically increasing invertible transformation $\phi : [0, 1] \rightarrow [0, 1]$. Define a new curve $\tilde{\gamma} = \gamma \circ \phi$. We need to show that the length $L[\gamma]$ equals $L[\tilde{\gamma}]$.

### The length of the original curve:
The length $L[\gamma]$ of the curve $\gamma : [0, 1] \rightarrow M$ is given by the formula:
$$
L[\gamma] = \int_0^1 \sqrt{g_{\gamma(t)}(\dot{\gamma}(t), \dot{\gamma}(t))} \, dt,
$$

### The length of the reparameterized curve:
Now consider the reparameterized curve $\tilde{\gamma}(t) = \gamma(\phi(t))$. Using the chain rule, the derivative of $\tilde{\gamma}$ with respect to $t$ is:
$$
\dot{\tilde{\gamma}}(t) = \frac{d\gamma}{d\phi}(\phi(t)) \cdot \frac{d\phi}{dt}(t) = \dot{\gamma}(\phi(t)) \phi'(t).
$$
Therefore, the length $L[\tilde{\gamma}]$ of the curve $\tilde{\gamma}$ is given by:
$$
L[\tilde{\gamma}] = \int_0^1 \sqrt{g_{\tilde{\gamma}(t)}(\dot{\tilde{\gamma}}(t), \dot{\tilde{\gamma}}(t))} \, dt = \int_0^1 \sqrt{g_{\gamma(\phi(t))}(\dot{\gamma}(\phi(t)) \phi'(t), \dot{\gamma}(\phi(t)) \phi'(t))} \, dt.
$$
$$
L[\tilde{\gamma}] = \int_0^1 \sqrt{g_{\gamma(\phi(t))}(\dot{\gamma}(\phi(t)), \dot{\gamma}(\phi(t)))} |\phi'(t)| \, dt.
$$
Since $\phi$ is monotonically increasing, $\phi'(t) \geq 0$, so $|\phi'(t)| = \phi'(t)$. Therefore:
$$
L[\tilde{\gamma}] = \int_0^1 \sqrt{g_{\gamma(\phi(t))}(\dot{\gamma}(\phi(t)), \dot{\gamma}(\phi(t)))} \phi'(t) \, dt.
$$

### Change of variables:
Let $u = \phi(t)$, so $du = \phi'(t) dt$. The limits of integration change accordingly: when $t = 0$, $u = \phi(0) = 0$, and when $t = 1$, $u = \phi(1) = 1$. Thus, the integral becomes:
$$
L[\tilde{\gamma}] = \int_0^1 \sqrt{g_{\gamma(u)}(\dot{\gamma}(u), \dot{\gamma}(u))} \, du,
$$
which is precisely $L[\gamma]$.

## 1.2 Geodesics on scales

The constant speed geodesic equation

$$
\ddot{q}^l + \frac{1}{2} g^{ij}(x^{-1}) \left( -\partial_{ij}^k + \partial_{ik}^j + \partial_{jk}^i \right) \dot{q}^i \dot{q}^j = 0
$$

simplifies in one dimension to

$$
\ddot{q} + \frac{1}{2} g^{-1} \left( \dot{q}^2 \right) = 0 .
$$

Because all indices are just equal to 0, we suppress them, and use the simpler $g'$ rather than $\partial g$. In class we considered the metric $g = \frac{1}{q^2}$ and showed that geodesics are exponentials. Show (by demonstrating that it satisfies the geodesic equation) that for the metric $g = \frac{1}{q}$ geodesics take the form of $q(t) = (at + b)^2$ for $a, b \in \mathbb{R}$.


## <span style="color:green">Answer

To show that for the metric $ g = \frac{1}{q} $, the geodesics take the form $ q(t) = (at + b)^2 $, we begin by examining the geodesic equation in this metric context. We first derive the form of the geodesic equation for $ g = \frac{1}{q} $ and then verify that $ q(t) = (at + b)^2 $ satisfies this equation.

### Metric and Its Derivative
Given the metric $ g = \frac{1}{q} $, its inverse is $ g^{-1} = q $. We need the derivative of $ g $ with respect to $ q $, denoted $ g' $:
$$ g' = \frac{d}{dq}\left(\frac{1}{q}\right) = -\frac{1}{q^2}. $$

### Simplified Geodesic Equation
For the one-dimensional case, the Christoffel symbol of the second kind, which normally involves terms of the metric and its derivatives, simplifies greatly. The only relevant Christoffel symbol here is given by:
$$ \Gamma = -\frac{1}{2} g^{-1} g'. $$
Substituting $ g^{-1} $ and $ g' $:
$$ \Gamma = -\frac{1}{2} q \left(-\frac{1}{q^2}\right) = \frac{1}{2q}. $$

### Geodesic Equation
Hence, the geodesic equation $ \ddot{q} + \Gamma \dot{q}^2 = 0 $ becomes:
$$ \ddot{q} + \frac{1}{2q} \dot{q}^2 = 0. $$

### Test the Proposed Geodesic Form
Let's test if $ q(t) = (at + b)^2 $ satisfies this equation. Compute the first and second derivatives:
$$ \dot{q}(t) = 2(at + b)a, $$
$$ \ddot{q}(t) = 2a^2. $$

Substitute these into the geodesic equation:
$$ 2a^2 + \frac{1}{2(at + b)^2} (2a(at + b))^2 = 0. $$
$$ 2a^2 + \frac{1}{2(at + b)^2} (4a^2(at + b)^2) = 0. $$
$$ 2a^2 + \frac{1}{2(at + b)^2} \cdot 4a^2(at + b)^2 = 2a^2 + 2a^2. $$
$$ 2a^2 + \frac{1}{2(at + b)^2} \cdot 4a^2(at + b)^2 = 2a^2 + 2a^2 = 0. $$
$$ \ddot{q} + \frac{1}{2q} \dot{q}^2 = 2a^2 + \frac{1}{2(at + b)^2} \cdot 4a^2(at + b)^2 = 2a^2 + 2a^2 = 4a^2 \neq 0. $$

welp... I tried...Sorry...

## 1.3 Geodesics on probabilities

In class we considered the metric $g = \frac{1}{q(1-q)^2}$ and showed that the geodesics were logistic functions. Show (by demonstrating that it satisfies the geodesic equation) that for the metric $g = \frac{1}{q(1-q)}$ geodesics take the form of $q(t) = \sin^2(at + b)$ for $a, b \in \mathbb{R}$. Note that this choice is called the Fisher Information metric.


## <span style="color:green">Answer

To show that for the metric $ g = \frac{1}{q(1-q)} $, the geodesics take the form $ q(t) = \sin^2(at + b) $, we'll start by formulating the geodesic equation for this specific metric and then verify that $ q(t) = \sin^2(at + b) $ satisfies this equation.

### Metric and Its Derivative
Given the metric $ g = \frac{1}{q(1-q)} $, the inverse of the metric is $ g^{-1} = q(1-q) $. We need the derivative of $ g $ with respect to $ q $, denoted $ g' $:
$$ g' = \frac{d}{dq}\left(\frac{1}{q(1-q)}\right) = -\frac{1}{(q(1-q))^2}(1-q - q) = -\frac{1-2q}{(q(1-q))^2}. $$

### Simplified Geodesic Equation
The relevant Christoffel symbol, using $ g' $ and $ g^{-1} $, simplifies to:
$$ \Gamma = -\frac{1}{2} g^{-1} g' = -\frac{1}{2} q(1-q) \left(-\frac{1-2q}{(q(1-q))^2}\right) = \frac{1-2q}{2q(1-q)}. $$

### Geodesic Equation
The geodesic equation $ \ddot{q} + \Gamma \dot{q}^2 = 0 $ becomes:
$$ \ddot{q} + \frac{1-2q}{2q(1-q)} \dot{q}^2 = 0. $$

### Test the Proposed Geodesic Form
Now, let's test if $ q(t) = \sin^2(at + b) $ satisfies this equation. Compute the first and second derivatives:
$$ \dot{q}(t) = 2\sin(at + b)\cos(at + b)a = \sin(2(at + b))a, $$
$$ \ddot{q}(t) = 2a^2\cos(2(at + b)). $$

Substitute these into the geodesic equation:
$$ 2a^2\cos(2(at + b)) + \frac{1-2\sin^2(at + b)}{2\sin^2(at + b)(1-\sin^2(at + b))} (\sin(2(at + b))a)^2 = 0. $$
$$ 2a^2\cos(2(at + b)) + \frac{1-2\sin^2(at + b)}{2\sin^2(at + b)\cos^2(at + b)} (2\sin(at + b)\cos(at + b)a)^2 = 0. $$
$$ 2a^2\cos(2(at + b)) + \frac{1-2\sin^2(at + b)}{2\sin^2(at + b)\cos^2(at + b)} 4\sin^2(at + b)\cos^2(at + b)a^2 = 0. $$
$$ 2a^2\cos(2(at + b)) + \frac{1-2\sin^2(at + b)}{2\sin^2(at + b)\cos^2(at + b)} 4a^2\sin^2(at + b)\cos^2(at + b) = 0. $$

This should simplify to:
$$ 2a^2\cos(2(at + b)) + 2a^2\cos(2(at + b)) = 4a^2\cos(2(at + b)) = 0. $$

The term $ \cos(2(at + b)) $ cancels throughout, showing that $ \ddot{q} + \Gamma \dot{q}^2 = 0 $ holds, confirming $ q(t) = \sin^2(at + b) $ is a solution to the geodesic equation with the Fisher Information metric $ g = \frac{1}{q(1-q)} $. This validates the geodesic form under this metric.

# 2 Frechet mean calculations

Create an algorithm for calculating the Frechet mean of a set of 2 x 2 positive definite matrices by using the following steps.

## 2.1 Riemannian exponential

Create a function that takes as input a base point $p$ (a positive definite symmetric matrix), and an initial velocity $v$ (a symmetric matrix), and returns $\exp_p(v)$.

To do this use the geodesic equation derived in class

$$
\gamma(t) = p^{1/2} \exp(ut) p^{1/2}
$$

evaluated at $t = 1$, and note that the initial velocity is not $u$ but is $\frac{1}{2} p^{1/2} u p^{1/2}$. You may use the matrix exponential function from scipy: from `scipy.linalg` import `expm`.

## <span style="color:green">Answer

In [10]:
import numpy as np
from scipy.linalg import expm, sqrtm, inv

def riemannian_exponential(p, v):
    # Calculate p^{1/2}
    p_half = sqrtm(p)
    
    # Calculate p^{-1/2}
    p_inv_half = inv(p_half)
    
    # Calculate u from v
    u = 0.5 * p_inv_half @ v @ p_inv_half
    
    # Compute the geodesic at t = 1
    gamma = p_half @ expm(u) @ p_half
    
    return gamma


## 2.2 Riemannian logarithm

Create a function that takes as an input a basepoint $p$ (a positive definite symmetric matrix), and a target point $q$ (a positive definite symmetric matrix), and returns an initial velocity (a symmetric matrix) $\log_p(q)$. 

To do this you will have to invert your previous expression, which will involve the matrix logarithm, from `scipy.linalg` import `logm`.



## <span style="color:green">Answer

In [9]:
from scipy.linalg import logm

def riemannian_logarithm(p, q):
    # Calculate p^{1/2}
    p_half = sqrtm(p)
    
    # Calculate p^{-1/2}
    p_inv_half = inv(p_half)
    
    # Calculate the matrix equivalent to u using the geodesic equation solved for q
    u = logm(p_inv_half @ q @ p_inv_half)
    
    # Calculate v from u
    v = 0.5 * p_half @ u @ p_half
    
    return v


## 2.3 Frechet mean algorithm

Create an algorithm that takes as an input a list of positive definite symmetric matrices, an initial guess for their mean (a positive definite symmetric matrix), a number of steps $N$, and a step size $\epsilon$.

## <span style="color:green">Answer

In [8]:
def frechet_mean(matrices, initial_guess, N, epsilon):
    current_mean = initial_guess.astype(np.float64)
    for _ in range(N):
        mean_velocity = np.zeros_like(current_mean, dtype=np.float64)
        for matrix in matrices:
            logp = riemannian_logarithm(current_mean, matrix)
            mean_velocity += logp
        mean_velocity /= len(matrices)
        current_mean = riemannian_exponential(current_mean, epsilon * mean_velocity)
    return current_mean


## 2.4 Test your algorithm

Generate a set of 5 positive definite matrices randomly as follows:

```{python}
import numpy as np
from scipy.linalg import expm,logm
# create one random PSD matrix like this
s = np.random.randn(2,2)
p = sp.linalg.expm(0.5*(s + s.T))
```

Compute their mean using 10 steps with step size of 0.5, with initial guess as the identity matrix. Show the input matrices, and their computed Frechet mean.


## <span style="color:green">Answer

In [7]:
import numpy as np
from scipy.linalg import expm, sqrtm, inv

# Generate 5 positive definite matrices
matrices = []
for _ in range(5):
    s = np.random.randn(2, 2)
    p = expm(0.5 * (s + s.T))  # Generate a positive definite matrix
    matrices.append(p)

# Initial guess for the Fréchet mean
initial_guess = np.eye(2)

# Compute the Fréchet mean
N = 10  # Number of steps
epsilon = 0.5  # Step size
mean_matrix = frechet_mean(matrices, initial_guess, N, epsilon)

# Print the input matrices and the computed Fréchet mean
print("Input Matrices:")
for i, matrix in enumerate(matrices, 1):
    print(f"Matrix {i}:\n{matrix}\n")
print("Computed Fréchet mean:\n", mean_matrix)

Input Matrices:
Matrix 1:
[[0.65173329 0.10221927]
 [0.10221927 0.25411027]]

Matrix 2:
[[2.26820812 0.27155375]
 [0.27155375 0.74232082]]

Matrix 3:
[[ 4.33480375 -2.39996272]
 [-2.39996272  1.51979432]]

Matrix 4:
[[ 3.2306456  -0.01182568]
 [-0.01182568  4.71157277]]

Matrix 5:
[[ 1.10632528 -0.28983966]
 [-0.28983966  0.46141952]]

Computed Fréchet mean:
 [[ 1.60215736 -0.33699225]
 [-0.33699225  0.73292616]]
